### ISSUE TITLE
Duplicate sms 

### ISSUE THREAD

**Issue by coscho** [appleboy/CodeIgniter-Nexmo-Message#11]
Hello and thank you for you library. 

I found an issue ... 

I have $respons = $this->nexmo->send_message($from, $to, $message); 

when I dump response ... 
<pre style="background: #FFFEEF; color: #000; border: 1px dotted #000; padding: 10px; margin: 10px 0
; text-align: left;">Dump => array(2) {
  ["message-count"] => string(1) "2"
  ["messages"] => array(2) {
    [0] => array(6) {
      ["to"] => string(11) "*********"
      ["message-id"] => string(16) "02000000C74FE314"
      ["status"] => string(1) "0"
      ["remaining-balance"] => string(10) "6.72440000"
      ["message-price"] => string(10) "0.05910000"
      ["network"] => string(5) "22603"
    }
    [1] => array(6) {
      ["to"] => string(11) "*********"
      ["message-id"] => string(16) "02000000C74FE315"
      ["status"] => string(1) "0"
      ["remaining-balance"] => string(10) "6.66530000"
      ["message-price"] => string(10) "0.05910000"
      ["network"] => string(5) "22603"
    }
  }
}
</pre>

THE ISSUE IS THAT SMS is duplicated that means that the **COSTS ARE DOUBLE**.

Where there issue comes from ??? PLEASE HELP

**Comment by appleboy** [comment]
Hi,

I think the messages you send are out of maximum length. You can see the detail `message` limitation.

https://docs.nexmo.com/api-ref/sms-api#mlength

**Comment by coscho** [comment]
Thank you very much.
